"""Generate Detailed_Tools.md from the live tool registry.

This repo treats the Python code as the source of truth.
Tool docs should be regenerated when the tool surface or schemas change.

Usage:
  python scripts/generate_detailed_tools.py > Detailed_Tools.md
"""

from __future__ import annotations

import json
import os
import sys

# Ensure repository root is on sys.path when invoked as a script.
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

import main  # noqa: E402


def _as_json(obj: object) -> str:
    return json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=False)


def main_cli() -> None:
    catalog = main.list_all_actions(include_parameters=True, compact=False)
    tools = list(catalog.get("tools", []))
    tools.sort(key=lambda t: (t.get("name") or ""))

    lines: list[str] = []
    lines.append("# Detailed tools reference (generated)\n\n")
    lines.append(
        "This file is generated from the running tool registry via "
        "`main.list_all_actions(include_parameters=True, compact=False)`.\n\n"
    )
    lines.append(
        "Do not edit this file by hand. Instead, update code/docstrings and regenerate:\n\n"
        "```bash\npython scripts/generate_detailed_tools.py > Detailed_Tools.md\n```\n\n"
    )

    lines.append(f"Total tools: {len(tools)}\n")

    for tool in tools:
        name = tool.get("name") or "<unknown>"
        description = (tool.get("description") or "").strip()
        write_action = bool(tool.get("write_action"))
        write_allowed = bool(tool.get("write_allowed"))
        write_auto_approved = bool(tool.get("write_auto_approved"))
        approval_required = bool(tool.get("approval_required"))
        write_enabled = bool(tool.get("write_enabled"))
        visibility = tool.get("visibility")
        ui_prompt_val = tool.get("ui_prompt")
        ui_prompt = ""
        if isinstance(ui_prompt_val, str):
            ui_prompt = ui_prompt_val.strip()
        elif ui_prompt_val is not None and ui_prompt_val is not False:
            ui_prompt = str(ui_prompt_val).strip()
        input_schema = tool.get("input_schema")

        lines.append(f"\n## {name}\n\n")
        if description:
            lines.append(description + "\n\n")

        lines.append("Metadata:\n")
        lines.append(f"- visibility: {visibility}\n")
        lines.append(f"- write_action: {write_action}\n")
        lines.append(f"- write_allowed: {write_allowed}\n")
        lines.append(f"- write_enabled: {write_enabled}\n")
        lines.append(f"- write_auto_approved: {write_auto_approved}\n")
        lines.append(f"- approval_required: {approval_required}\n")
        if ui_prompt:
            lines.append(f"- ui_prompt: {ui_prompt}\n")

        if input_schema is not None:
            lines.append("\nInput schema:\n\n```json\n")
            lines.append(_as_json(input_schema) + "\n")
            lines.append("```\n")

        lines.append("\nExample invocation:\n\n```json\n")
        lines.append(_as_json({"tool": name, "args": {}}) + "\n")
        lines.append("```\n")

    sys.stdout.write("".join(lines))


if __name__ == "__main__":
    main_cli()
