# AdaptivMCP Windows 11 launcher
[CmdletBinding()]
param(
    [int]$Port = 8000,
    [switch]$InstallOnly
)
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $Root
$Venv = Join-Path $Root ".venv"
$EnvFile = Join-Path $Root ".env"
$VenvPython = Join-Path $Venv "Scripts\python.exe"

function Write-Step([string]$Message) { Write-Host "==> $Message" -ForegroundColor Cyan }

function Get-PythonCommand {
    if (Get-Command py -ErrorAction SilentlyContinue) {
        try {
            & py -3.12 -c "import sys; print(sys.version_info[:2] == (3, 12))" 2>$null
            if ($LASTEXITCODE -eq 0) { return @("py", "-3.12") }
        } catch {}
    }
    if (Get-Command python -ErrorAction SilentlyContinue) {
        $ok = & python -c "import sys; print(sys.version_info[:2] == (3, 12))" 2>$null
        if ($LASTEXITCODE -eq 0 -and $ok -eq "True") { return @("python") }
    }
    throw "Python 3.12 is required. Install Python 3.12 from https://www.python.org/downloads/windows/ and run this script again."
}

function Invoke-Python([string[]]$Arguments) {
    $cmd = Get-PythonCommand
    if ($cmd.Count -eq 1) { & $cmd[0] @Arguments }
    else { & $cmd[0] $cmd[1] @Arguments }
    if ($LASTEXITCODE -ne 0) { throw "Python command failed with exit code $LASTEXITCODE." }
}

function Ensure-Prerequisites {
    Write-Step "Checking Windows prerequisites"
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw "Git for Windows is required. Install it from https://git-scm.com/download/win and run this script again."
    }
    $null = Get-PythonCommand
    Write-Host "Python 3.12 and Git are available." -ForegroundColor Green
}

function Ensure-Venv {
    Write-Step "Creating/updating the Python virtual environment"
    if (-not (Test-Path $VenvPython)) { Invoke-Python @("-m", "venv", $Venv) }
    & $VenvPython -m pip install --upgrade pip setuptools wheel
    if ($LASTEXITCODE -ne 0) { throw "Failed to upgrade pip tooling." }
    & $VenvPython -m pip install -r (Join-Path $Root "requirements.txt")
    if ($LASTEXITCODE -ne 0) { throw "Failed to install AdaptivMCP dependencies." }
}

function Ensure-EnvFile {
    if (Test-Path $EnvFile) {
        Write-Host "Using existing .env file." -ForegroundColor Green
        return
    }
    Write-Step "Creating local .env configuration"
    $githubToken = Read-Host "GitHub token (required; input is hidden)"
    if ([string]::IsNullOrWhiteSpace($githubToken)) { throw "A GitHub token is required." }
    $authToken = & $VenvPython -c "import secrets; print(secrets.token_urlsafe(32))"
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($authToken)) { throw "Could not generate the local MCP authentication token." }
    $lines = @(
        "# Generated by scripts/windows-start.ps1. Do not commit this file.",
        "ADAPTIV_MCP_AUTH_TOKEN=$authToken",
        "GITHUB_TOKEN=$githubToken",
        "GITHUB_API_BASE=https://api.github.com",
        "ADAPTIV_MCP_ALLOWED_HOSTS=127.0.0.1,localhost",
        "ADAPTIV_MCP_ALLOWED_ORIGINS=http://127.0.0.1:$Port,http://localhost:$Port",
        "MCP_WORKSPACE_BASE_DIR=$([Environment]::GetFolderPath('LocalApplicationData'))\AdaptivMCP\workspaces",
        "PORT=$Port"
    )
    Set-Content -Path $EnvFile -Value $lines -Encoding UTF8
    Write-Host ".env created at $EnvFile" -ForegroundColor Green
}

function Import-EnvFile {
    foreach ($line in Get-Content $EnvFile) {
        if ($line -match '^\s*#' -or $line -notmatch '^\s*([^=]+)=(.*)$') { continue }
        [Environment]::SetEnvironmentVariable($Matches[1].Trim(), $Matches[2], "Process")
    }
}

Ensure-Prerequisites
Ensure-Venv
Ensure-EnvFile
Import-EnvFile

if ($InstallOnly) {
    Write-Host "Setup complete. Start AdaptivMCP with launch-windows.cmd or this script." -ForegroundColor Green
    exit 0
}

Write-Step "Starting AdaptivMCP"
Write-Host "MCP endpoint: http://127.0.0.1:$Port/mcp"
Write-Host "Health check: http://127.0.0.1:$Port/healthz"
Write-Host "Press Ctrl+C to stop."

& $VenvPython -m uvicorn main:app --host 127.0.0.1 --port $Port
